### ISSUE TITLE
Would kindly suggest that this lesson is redone

### ISSUE THREAD

**Issue by alexander-mc** [learn-co-curriculum/creating-columns-based-layouts-in-css#3]
First, I've greatly enjoyed all material up to this point! Unfortunately, this one and the previous one seems a little off!

I ended up spending hours trying to make sense of the material, and then just resorted to picking out what I could from the websites in the resources section.

My biggest suggestion would be to add graphics! A large part of CSS is about creating visuals, and so CSS concepts are difficult to learn without images. This entire lesson (a long one, too) doesn't have one image... it's like teaching someone how to paint from a textbook without any pictures. Very difficult...

Another way of redoing this lesson is just to make it a code along! That would help greatly.

**Comment by Sdcrouse** [comment]
There actually are a couple of graphics; they just won't render for some reason.

The issue I raised at https://github.com/learn-co-curriculum/creating-column-based-layouts-in-css/issues/5 should help.

**Comment by alexander-mc** [comment]
Thanks!

**Comment by Sdcrouse** [comment]
No problem.
